server.port=8085
spring.application.name=gateway-service

# Desactivar Config Server en el gateway
spring.cloud.config.enabled=false
spring.cloud.config.import-check.enabled=false

# ==== RUTA PRODUCTOS ====
# Para desarrollo local: usar localhost
# Para producción/VM: cambiar a la IP o dominio de la máquina virtual
# Ejemplo: http://192.168.1.100:8082
spring.cloud.gateway.routes[0].id=product-direct
spring.cloud.gateway.routes[0].uri=http://localhost:8082
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/productos/**

# Logs extra
logging.level.org.springframework=INFO
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.com.cloud.gateway=DEBUG

# Eureka
# Para desarrollo local: usar localhost
# Para producción/VM: cambiar a la IP o dominio de la máquina virtual
# Ejemplo: http://192.168.1.100:8761/eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# ==== RUTA AUTH ====
# Para desarrollo local: usar localhost
# Para producción/VM: cambiar a la IP o dominio de la máquina virtual
# Ejemplo: http://192.168.1.100:8081
spring.cloud.gateway.routes[1].id=auth-direct
spring.cloud.gateway.routes[1].uri=http://localhost:8081
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/auth/**

# ==== RUTA PEDIDOS ====
# Para desarrollo local: usar localhost
# Para producción/VM: cambiar a la IP o dominio de la máquina virtual
# Ejemplo: http://192.168.1.100:8084
spring.cloud.gateway.routes[2].id=orders-direct
spring.cloud.gateway.routes[2].uri=http://localhost:8084
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/pedidos/**

# ==== RUTA BOLETAS ====
# Para desarrollo local: usar localhost
# Para producción/VM: cambiar a la IP o dominio de la máquina virtual
# Ejemplo: http://192.168.1.100:8084
spring.cloud.gateway.routes[3].id=boletas-direct
spring.cloud.gateway.routes[3].uri=http://localhost:8084
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/boletas/**

# ==== RUTA REPORTES ====
# Para desarrollo local: usar localhost
# Para producción/VM: cambiar a la IP o dominio de la máquina virtual
# Ejemplo: http://192.168.1.100:8086
spring.cloud.gateway.routes[4].id=reports-direct
spring.cloud.gateway.routes[4].uri=http://localhost:8086
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/reportes/**